name: 노드 전체 빌드

on:
  workflow_call:

jobs:
  build:
    name: build-node
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Node 16 배포
      run: sh ./node16/upload.sh $(date +%s)
